import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BtnFinal from "@/components/BtnFinal";
import Footer from "@/components/Footer";

const poppins = Poppins({ 
  weight: ["100","200","300", "400","500", "600", "700","800","900"],
  subsets: ["latin"]
 });

export const metadata: Metadata = {
  title: "Short url",
  description: "Generated by create next app",
  icons: "/img/logo.svg"
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={poppins.className}>
        <main className="w-full h-full bg-background flex flex-col items-center">
          <Header />
          {children}
          <BtnFinal />
          <Footer /> 
        </main>
      </body>
    </html>
  );
}
